### ISSUE TITLE
it is not possible to run

### ISSUE THREAD

**Issue by tazik561** [may-andro/weighter#3]
hello  . I download your project and i want to run on emulator but i got this error :
`Build file '/mnt/Projects/Projects/Practices/gitProject/flutter-cleanarch-weight-management-app/android/app/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'`

How can i run ?

**Comment by may-andro** [comment]
Hi,
Try the patch file I have sent. It is happening because of the Flutter
version updates and library I used have updated. Try to apply the patch and
tell me if it doesn't work.

Regards,
Mayank Rai
